name: Canary

on:
  push:
    branches:
      - main

jobs:
  canary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Enable Corepack
        run: npm i -g corepack

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish
        run: sh scripts/publish-prerelease.sh
        env:
          REGISTRY_AUTH_TOKEN: ${{ secrets.VERDACCIO_REGISTRY_TOKEN_CANARY }}
          REGISTRY_URL: ${{ values.CANARY_REGISTRY }}
